import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/constants/app_routes.dart';
import '../../../../core/utils/formatters.dart';
import '../../../../shared/components/primary_button.dart';
import '../../../subscription/domain/entities/subscription_state.dart';
import '../../../subscription/presentation/controllers/subscription_controller.dart';
import '../../domain/entities/invoice.dart';
import '../controllers/invoices_controller.dart';
import 'invoice_pdf_preview_screen.dart';

class InvoiceDetailScreen extends ConsumerStatefulWidget {
  const InvoiceDetailScreen({super.key, required this.invoiceId});

  final String invoiceId;

  @override
  ConsumerState<InvoiceDetailScreen> createState() =>
      _InvoiceDetailScreenState();
}

class _InvoiceDetailScreenState extends ConsumerState<InvoiceDetailScreen> {
  bool _isExporting = false;

  Future<void> _openPdfPreview(Invoice invoice) async {
    if (_isExporting) {
      return;
    }

    setState(() => _isExporting = true);

    try {
      await Navigator.of(context).push<void>(
        MaterialPageRoute<void>(
          builder: (_) => InvoicePdfPreviewScreen(invoiceId: invoice.id),
        ),
      );

      if (!mounted) {
        return;
      }

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            subscriptionIsPro(ref)
                ? 'PDF ready to preview and share.'
                : 'PDF preview opened. Free plan PDFs include the Invoice Flow footer watermark.',
          ),
          action: subscriptionIsPro(ref)
              ? null
              : SnackBarAction(
                  label: 'Upgrade',
                  onPressed: () {
                    const UpgradeToProRoute().push(context);
                  },
                ),
        ),
      );
    } catch (_) {
      if (!mounted) {
        return;
      }

      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Unable to export the invoice PDF right now.'),
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _isExporting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final invoiceState = ref.watch(invoiceDetailProvider(widget.invoiceId));
    final subscription =
        ref.watch(subscriptionControllerProvider).valueOrNull ??
        const SubscriptionState.free();

    return Scaffold(
      appBar: AppBar(
        title: const Text('Invoice Detail'),
        actions: [
          IconButton(
            onPressed: () => EditInvoiceRoute(widget.invoiceId).push(context),
            icon: const Icon(Icons.edit_outlined),
          ),
        ],
      ),
      body: invoiceState.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error, stack) => Center(child: Text(error.toString())),
        data: (invoice) {
          if (invoice == null) {
            return const Center(child: Text('Invoice not found'));
          }

          return ListView(
            padding: const EdgeInsets.fromLTRB(20, 20, 20, 100),
            children: [
              Text(
                invoice.clientName,
                style: Theme.of(context).textTheme.headlineMedium,
              ),
              const SizedBox(height: 8),
              Text(
                invoice.service,
                style: Theme.of(context).textTheme.titleLarge,
              ),
              const SizedBox(height: 16),
              _InfoRow(
                label: 'Amount',
                value: AppFormatters.currency(
                  invoice.amount,
                  currencyCode: invoice.currencyCode,
                ),
              ),
              _InfoRow(
                label: 'Due Date',
                value: AppFormatters.shortDate(invoice.dueDate),
              ),
              _InfoRow(label: 'Status', value: invoice.status.label),
              const SizedBox(height: 20),
              PrimaryButton(
                label: 'Send Reminder',
                icon: Icons.send_rounded,
                onPressed: () => ReminderFlowRoute(invoice.id).push(context),
              ),
              const SizedBox(height: 10),
              OutlinedButton.icon(
                onPressed: _isExporting ? null : () => _openPdfPreview(invoice),
                icon: const Icon(Icons.picture_as_pdf_outlined),
                label: Text(_isExporting ? 'Opening PDF...' : 'Open PDF'),
              ),
              if (!subscription.isPro) ...[
                const SizedBox(height: 10),
                Text(
                  'Free plan PDFs include the "Generated by Invoice Flow" footer watermark.',
                  style: Theme.of(context).textTheme.bodySmall,
                ),
              ],
              const SizedBox(height: 10),
              OutlinedButton.icon(
                onPressed: invoice.status == InvoiceStatus.paid
                    ? null
                    : () async {
                        await ref
                            .read(invoicesControllerProvider.notifier)
                            .updateInvoice(
                              invoice.copyWith(status: InvoiceStatus.paid),
                            );
                        ref.invalidate(invoiceDetailProvider(invoice.id));
                      },
                icon: const Icon(Icons.check_circle_outline),
                label: const Text('Mark as Paid'),
              ),
            ],
          );
        },
      ),
    );
  }
}

bool subscriptionIsPro(WidgetRef ref) {
  final subscription = ref.read(subscriptionControllerProvider).valueOrNull;
  return subscription?.isPro ?? false;
}

class _InfoRow extends StatelessWidget {
  const _InfoRow({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 6),
      child: Row(
        children: [
          Expanded(child: Text(label)),
          Text(value),
        ],
      ),
    );
  }
}
